name: suai_leetcode_bot
version: 1.1.0
repository: https://github.com/cocahonka/suai-leetcode-bot

environment:
  sdk: ^3.2.6

dependencies:
  collection: ^1.18.0
  drift: ^2.15.0
  excel: ^4.0.2
  http: ^1.2.0
  meta: ^1.12.0
  path: ^1.8.0
  sqlite3: ^2.4.0
  televerse: ^1.14.0

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  very_good_analysis: ^5.1.0
